# Redirect all routes to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

# Redirect API requests to your backend server
[[redirects]]
  from = "/api/*"
  to = "https://library-app-backend-ya07.onrender.com/api/:splat"
  status = 200
  force = true
